### ISSUE TITLE
_th_or not supported on CUDAType for Bool

### ISSUE THREAD

**Issue by Marcus208** [Xiangyu-CAS/R2CNN.pytorch#1]
2019-08-15 17:22:58,154 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/tools/train_net.py", line 176, in <module>
    main()
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/tools/train_net.py", line 74, in train
    arguments,
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/maskrcnn_benchmark/engine/trainer.py", line 64, in do_train
    loss_dict = model(images, targets)
  File "/home/room304/anaconda3/envs/pytorch120-cuda90/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/room304/anaconda3/envs/pytorch120-cuda90/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 26, in forward
    x, detections, loss_box = self.box(features, proposals, targets)
  File "/home/room304/anaconda3/envs/pytorch120-cuda90/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 43, in forward
    proposals = self.loss_evaluator.subsample(proposals, targets)
  File "/home/room304/lichengyuan/saliency-RS/R2CNN.pytorch/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py", line 124, in subsample
    img_sampled_inds = torch.nonzero(pos_inds_img | neg_inds_img).squeeze(1)
RuntimeError: _th_or not supported on CUDAType for Bool

what can i do?
hope for your help
conda-env: python-3.5 cuda9.0 pytorch1.1.0

**Comment by Xiangyu-CAS** [comment]
I think it is caused by the newest version feature of pytorch1.2.0, which replace torch.uint8 to torch.bool. 
You can update your pytorch to 1.2.0 or replace all "torch.bool" by "torch.uint8"

**Comment by etrigger** [comment]
@Marcus208 Have you solved the problem? I have the same error as yours.

**Comment by Xiangyu-CAS** [comment]
@etrigger  Did you check your pytorch version?

**Comment by Marcus208** [comment]
@Xiangyu-CAS @etrigger when i change the pytorch to version=1.2.0, it works well! THX

**Comment by etrigger** [comment]
hi，thanks for your info.
My pytorch is 1.1. I changed the type of pos_inds_img and neg_inds_img  in loss.py to uint8, and now it works OK.
