### ISSUE TITLE
'BoxList' object has no attribute 'quad_bbox'

### ISSUE THREAD

**Issue by yoyoyo-yo** [Xiangyu-CAS/R2CNN.pytorch#2]

**Comment by yoyoyo-yo** [comment]
Thank you for your gread job!

I installed and used inference_engine.py. Then, I got

```
Traceback (most recent call last):
  File "inference_engine.py", line 230, in <module>
    canvas = detector.run_on_opencv_image(img)
  File "inference_engine.py", line 93, in run_on_opencv_image
    result = self.overlay_boxes(result, top_predictions)
  File "inference_engine.py", line 172, in overlay_boxes
    quad_boxes = predictions.quad_bbox
AttributeError: 'BoxList' object has no attribute 'quad_bbox'
```

What shold I do?

**Comment by AlfengYuan** [comment]
This implement doesn't include 11x3 and 3x11 RoiAligan or RoiPooling, and inclined nms agorithm.
 This is a good project for learning, but it is too far from the original paper.

**Comment by Xiangyu-CAS** [comment]
@yoyoyo-yo It seems like you have installed the original version of MaskRCNN-benchmark, so it points to another BoxList class, which has no implementation of Quad_bbox.

**Comment by Xiangyu-CAS** [comment]
@yyfhaku This version only implemented the major though of R2CNN, that's the rotated region regression. Actually, there are still lots of hyperparamters and tricks need to be carefully adjusted.
 
BTW: 11*3 and 3*11 proved to be not working well in general case

**Comment by yangkai798** [comment]
嗨， 请问这里最后预测的还是按照8个点来吗？而不是论文中说的, x1, y1, x2, y2 和h?  Inclined NMS 算IoU的时候实际上就是Skew IoU 是吗？ 多谢！

**Comment by AlfengYuan** [comment]
是啊，你是对的，这个跟论文完全不一样，但是可以学习，可以参考它的自己定义数据流，试着去复现



---Original---

**Comment by yoyoyo-yo** [comment]
@Xiangyu-CAS I followed your INSTALL.md, but got same error.
This looks like maskrcnn_benchmark path error?

**Comment by xiabc612** [comment]
There is no need to clone another maskrcnn-benchmark, just run  "python setup.py build develop" in root dir. The installation instructions need to be improved!

**Comment by Xiangyu-CAS** [comment]
@xiabc612 you are right... I didn't update installation.md, so it's the same as maskrcnn-benchmark. I will revise it. Thank you

**Comment by Xiangyu-CAS** [comment]
@yoyoyo-yo as xiabc612 said， there's no need to git clone another maskrcnn-benchmark, I have updated installation instructions. It's my fault, sorry for it.

**Comment by Xiangyu-CAS** [comment]
@yangkai798 是按照4个点8个参数来的，[x1, y1, x2, y2, h]也可以，后者效果在ICDAR上更好一点点，但区别应该不大，用在遥感里大家更倾向用4个点。 Inclinded NMS这里还没实现...

**Comment by YQ-Yang** [comment]
请问这个能否在自己的数据集实现？
